/**
 * Built-in Workflow Templates
 *
 * v0.8.0: Pre-built workflow templates that users can instantiate
 */

import type { WorkflowTemplate } from "./types";

export const BUILT_IN_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "tpl-webhook-to-slack",
    name: "Webhook to Slack",
    description: "Receive webhook, process with Claude, post to Slack",
    category: "Notifications",
    tags: ["webhook", "slack", "notifications"],
    version: "1.0.0",
    icon: "webhook",
    isBuiltIn: true,
    nodes: [
      {
        id: "webhook-trigger",
        label: "Webhook Trigger",
        description: "Receive incoming HTTP requests",
        type: "trigger",
        x: 50,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        config: {
          params: {},
          webhook: { path: "/my-webhook", method: "POST" },
        },
      },
      {
        id: "process-payload",
        label: "Process Payload",
        description: "Transform and validate incoming data",
        type: "variable",
        x: 280,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        variableOps: [
          { op: "set", name: "message", value: "$trigger.body.message" },
        ],
      },
      {
        id: "claude-process",
        label: "Claude Process",
        description: "Analyze and format message with AI",
        type: "action",
        x: 510,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "notify-slack",
        label: "Post to Slack",
        description: "Send formatted message to Slack channel",
        type: "service",
        service: "slack",
        x: 740,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        config: {
          params: {
            channel: "#general",
            message: "{{message}}",
          },
        },
      },
    ],
    edges: [
      { from: "webhook-trigger", to: "process-payload", animated: true },
      { from: "process-payload", to: "claude-process" },
      { from: "claude-process", to: "notify-slack" },
    ],
    variables: [
      { name: "channel", description: "Slack channel to post to", defaultValue: "#general" },
    ],
  },
  {
    id: "tpl-parallel-deploy",
    name: "Parallel Deployment",
    description: "Deploy to multiple environments in parallel with retry",
    category: "CI/CD",
    tags: ["parallel", "deployment", "retry"],
    version: "1.0.0",
    icon: "git-merge",
    isBuiltIn: true,
    nodes: [
      {
        id: "trigger",
        label: "Deploy Trigger",
        description: "Start deployment process",
        type: "trigger",
        x: 50,
        y: 200,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "parallel-start",
        label: "Parallel Deploy",
        description: "Deploy to all environments simultaneously",
        type: "parallel",
        x: 280,
        y: 200,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        parallelChildren: ["deploy-staging", "deploy-prod"],
      },
      {
        id: "deploy-staging",
        label: "Deploy Staging",
        description: "Deploy to staging environment",
        type: "retry",
        x: 510,
        y: 100,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        retryConfig: {
          maxAttempts: 3,
          backoffType: "exponential",
          initialDelayMs: 1000,
          maxDelayMs: 30000,
        },
      },
      {
        id: "deploy-prod",
        label: "Deploy Production",
        description: "Deploy to production environment",
        type: "retry",
        x: 510,
        y: 300,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        retryConfig: {
          maxAttempts: 3,
          backoffType: "exponential",
          initialDelayMs: 2000,
          maxDelayMs: 60000,
        },
      },
      {
        id: "notify-complete",
        label: "Notify Complete",
        description: "Send deployment completion notification",
        type: "output",
        x: 740,
        y: 200,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
    ],
    edges: [
      { from: "trigger", to: "parallel-start", animated: true },
      { from: "parallel-start", to: "deploy-staging" },
      { from: "parallel-start", to: "deploy-prod" },
      { from: "deploy-staging", to: "notify-complete" },
      { from: "deploy-prod", to: "notify-complete" },
    ],
    variables: [
      { name: "stagingUrl", description: "Staging environment URL", required: true },
      { name: "prodUrl", description: "Production environment URL", required: true },
    ],
  },
  {
    id: "tpl-error-handling",
    name: "Error Handling Pipeline",
    description: "Process data with error handling and fallback",
    category: "Data Processing",
    tags: ["error-handling", "try-catch", "fallback"],
    version: "1.0.0",
    icon: "shield-alert",
    isBuiltIn: true,
    nodes: [
      {
        id: "trigger",
        label: "Data Input",
        description: "Receive data to process",
        type: "trigger",
        x: 50,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "try-block",
        label: "Try Process",
        description: "Attempt main processing",
        type: "try-catch",
        x: 280,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        catchNodeId: "error-handler",
        finallyNodeId: "cleanup",
      },
      {
        id: "main-process",
        label: "Main Process",
        description: "Primary data processing",
        type: "action",
        x: 510,
        y: 100,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "error-handler",
        label: "Error Handler",
        description: "Handle processing errors",
        type: "action",
        x: 510,
        y: 260,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "cleanup",
        label: "Cleanup",
        description: "Always runs after processing",
        type: "process",
        x: 740,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "output",
        label: "Output Result",
        description: "Return processing result",
        type: "output",
        x: 970,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
    ],
    edges: [
      { from: "trigger", to: "try-block", animated: true },
      { from: "try-block", to: "main-process", label: "try" },
      { from: "try-block", to: "error-handler", label: "catch" },
      { from: "main-process", to: "cleanup" },
      { from: "error-handler", to: "cleanup" },
      { from: "cleanup", to: "output" },
    ],
  },
  {
    id: "tpl-data-transform",
    name: "Data Transform Pipeline",
    description: "Transform data with variables and conditional logic",
    category: "Data Processing",
    tags: ["variables", "transform", "decision"],
    version: "1.0.0",
    icon: "variable",
    isBuiltIn: true,
    nodes: [
      {
        id: "input",
        label: "Data Input",
        description: "Receive input data",
        type: "trigger",
        x: 50,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "set-vars",
        label: "Set Variables",
        description: "Extract and set variables",
        type: "variable",
        x: 280,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        variableOps: [
          { op: "set", name: "count", value: "$trigger.items.length" },
          { op: "transform", name: "names", transform: "jq", expression: ".items | map(.name)" },
        ],
      },
      {
        id: "check-count",
        label: "Check Count",
        description: "Branch based on item count",
        type: "decision",
        x: 510,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
        config: {
          params: {},
          condition: "$count > 10",
        },
      },
      {
        id: "batch-process",
        label: "Batch Process",
        description: "Process in batches for large datasets",
        type: "action",
        x: 740,
        y: 100,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "direct-process",
        label: "Direct Process",
        description: "Process directly for small datasets",
        type: "action",
        x: 740,
        y: 260,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
      {
        id: "output",
        label: "Output Result",
        description: "Return processed data",
        type: "output",
        x: 970,
        y: 180,
        stats: { executions: 0, errors: 0, avgTimeMs: 0 },
        status: "idle",
      },
    ],
    edges: [
      { from: "input", to: "set-vars", animated: true },
      { from: "set-vars", to: "check-count" },
      { from: "check-count", to: "batch-process", label: "large" },
      { from: "check-count", to: "direct-process", label: "small" },
      { from: "batch-process", to: "output" },
      { from: "direct-process", to: "output" },
    ],
    variables: [
      { name: "batchSize", description: "Number of items per batch", defaultValue: "100" },
    ],
  },
];

export default BUILT_IN_TEMPLATES;
